import Image from "next/image";import Link from "next/link";import {Dumbbell,Handshake,MapPin,ShieldCheck,Target} from "lucide-react";import {instructors} from "@/data/instructors";import {dojos} from "@/data/dojos";import {events} from "@/data/events";import {site} from "@/data/site";import {GalleryGrid} from "@/components/GalleryGrid";import {AnimatedHeroLogo} from "@/components/AnimatedHeroLogo";import {SectionHeading} from "@/components/UI";
const featuredEvents=[...events].sort((a,b)=>a.status===b.status?b.date.localeCompare(a.date):a.status==="Upcoming"?-1:1).slice(0,3);
export default function Home(){return <><section className="home-hero">
  <div className="container home-hero__inner">
    <div className="home-hero__content">
      <p className="home-hero__brand">Darkan</p>
      <h1 className="home-hero__title">
        <span>Traditional Okinawan</span>
        <span>Goju-Ryu Karate-Do</span>
        <span>&amp; Kobudo</span>
      </h1>
      <div className="home-hero__affiliation" aria-label="Academy membership and affiliation">
        <p><strong>Member of:</strong> Sanbo Ken-Kai Goju-Ryu Karate-Do India <b>(SANBO)</b></p>
        <p><strong>Sanbo is affiliated with:</strong> TOGKF, Okinawa, Japan</p>
      </div>
    </div>
    <AnimatedHeroLogo/>
  </div>
  <span className="home-hero__kanji" aria-hidden="true">剛柔流</span>
</section>
<section className="academy-intro" aria-labelledby="academy-intro-title"><div className="container academy-intro__layout"><div className="academy-intro__lead"><p className="academy-intro__eyebrow">Established {site.established} · Tamil Nadu</p><h2 id="academy-intro-title" className="academy-intro__title">Traditional Okinawan karate, taught with clarity and purpose.</h2><p className="academy-intro__summary">Darkan Traditional Okinawan Goju-Ryu Karate-Do &amp; Kobudo Academy provides structured martial arts training for children and adults in Tamil Nadu. Classes develop sound technique, physical fitness, self-control and respect through regular, progressive practice.</p><div className="academy-intro__actions"><Link href="/dojos" className="btn btn-red">Find a dojo</Link><Link href="/about" className="btn">About the academy</Link></div><p className="academy-intro__affiliation"><span>Affiliation</span>{site.affiliation}</p></div><div className="academy-intro__programmes"><article><span>01</span><div><h3>Goju-Ryu Karate-Do</h3><p>Training in kihon, kata, partner exercises and practical application, with attention to posture, breathing, timing and control.</p></div></article><article><span>02</span><div><h3>Okinawan Kobudo</h3><p>Traditional weapons practice introduced progressively, with an emphasis on safe handling, coordination and correct fundamentals.</p></div></article><article><span>03</span><div><h3>Steady student development</h3><p>A consistent training path that supports discipline, confidence, fitness and responsibility at every stage of learning.</p></div></article></div></div></section>
<section className="values-strip" aria-label="Core training values"><div className="container values-strip__grid"><div><Target aria-hidden="true"/><span>Discipline</span></div><div><Handshake aria-hidden="true"/><span>Respect</span></div><div><Dumbbell aria-hidden="true"/><span>Strength</span></div><div><ShieldCheck aria-hidden="true"/><span>Character</span></div></div></section>
<section className="faculty-section" aria-labelledby="faculty-title"><div className="container faculty-grid"><header className="faculty-intro"><p>Authorised instruction</p><h2 id="faculty-title">Instructors who keep practice clear and consistent.</h2><div className="faculty-intro__rule"/><p className="faculty-intro__copy">Traditional Goju-Ryu Karate-Do and Kobudo taught through clear standards, patient correction and regular practice.</p></header>{instructors.map((p,i)=><article key={p.slug} className={`faculty-card faculty-card--${i+1}`}><figure><Image src={p.image} fill alt={`${p.name}, ${p.role}, teaching traditional Goju-Ryu Karate-Do`} className="object-contain" style={{objectPosition:p.imagePosition}} sizes="(min-width: 1000px) 32vw, (min-width: 650px) 50vw, 100vw"/><figcaption>{p.rank}</figcaption></figure><div className="faculty-card__body"><p className="faculty-card__role">{p.role}</p><h3>{p.name}</h3><p className="faculty-card__bio">{p.bio}</p><dl><div><dt>Dojo</dt><dd>{p.dojos.join(" · ")}</dd></div></dl></div></article>)}</div></section>
<section className="dojo-network" aria-labelledby="dojo-network-title"><div className="container"><header className="dojo-network__header"><div><p className="dojo-network__eyebrow">Training locations in Tamil Nadu</p><h2 id="dojo-network-title">Four dojos. One clear method.</h2></div><div className="dojo-network__philosophy"><span>Training philosophy</span><p>Consistency before intensity. Technique before speed. Courtesy throughout practice.</p></div></header><p className="dojo-network__intro">Choose a traditional Goju-Ryu Karate-Do and Kobudo class in Thiruverkadu, Ayyapanthangal or Thundalam. View the weekly schedule, meet the dojo instructor and open the exact training location directly in Google Maps.</p><div className="dojo-network__grid">{dojos.map((d,i)=><article key={d.slug} className="dojo-card"><div className="dojo-card__top"><span>0{i+1}</span><p>{d.area}</p></div><h3>{d.name}</h3><p className="dojo-card__schedule">{d.schedule.join(" · ")}</p><div className="dojo-card__meta"><div><span>Instructor</span><p>{d.instructor}</p></div><div><span>Suitable for</span><p>{d.ages}</p></div></div><a href={d.mapUrl} target="_blank" rel="noreferrer" className="dojo-card__map" aria-label={`Open ${d.name} location in Google Maps`}><span className="dojo-card__map-icon"><MapPin aria-hidden="true"/></span><span><small>Exact dojo location</small><strong>Open in Google Maps</strong></span><b aria-hidden="true">↗</b></a></article>)}</div></div></section>
<section className="event-board" aria-labelledby="event-board-title"><div className="container"><header className="event-board__header"><div><p>Gradings &amp; tournaments</p><h2 id="event-board-title">Karate events and key dates</h2></div><p>Follow upcoming belt grading and traditional karate tournament dates in Tamil Nadu. Students should confirm eligibility, reporting time and venue details with their instructor.</p><Link href="/events">Complete calendar <span aria-hidden="true">↗</span></Link></header><div className="event-board__list">{featuredEvents.map((event,i)=><article key={event.slug} className={event.status==="Upcoming"?"is-upcoming":""}><div className="event-board__index">0{i+1}</div><div className="event-board__date"><time dateTime={event.date}>{event.displayDate}</time><span>{event.status}</span></div><div className="event-board__main"><h3>{event.title}</h3><p>{event.description}</p></div><div className="event-board__place"><span>Location</span><p>{event.venue}</p></div><Link href="/events" aria-label={`View ${event.title} details for ${event.displayDate}`}>Details <span aria-hidden="true">→</span></Link></article>)}</div><p className="event-board__note">Event information is updated when dates and venues are confirmed.</p></div></section>
<section className="section bg-[#111] text-white"><div className="container"><SectionHeading eyebrow="From the dojo" title="Training, grading, growth."/><GalleryGrid limit={5}/><Link href="/gallery" className="btn mt-8 border-white">View gallery</Link></div></section>
<section className="section"><div className="container grid gap-8 md:grid-cols-[1fr_auto] md:items-end"><div><p className="eyebrow">Your first step</p><h2 className="title serif mt-4">Begin Your Karate Journey</h2><p className="muted mt-5 max-w-2xl">Parents, beginners and experienced martial artists are welcome to enquire. Tell us your preferred dojo and we’ll help you find a suitable class.</p></div><div className="flex flex-wrap gap-3"><a href={`tel:${site.phone}`} className="btn">Call the academy</a><Link href="/contact" className="btn btn-red">Send an enquiry</Link></div></div></section></>}
